import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useWallet } from '@solana/wallet-adapter-react';
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import { ChatButton, IncomingThemeVariables } from '@dialectlabs/react-ui';
import styles from '../styles/Home.module.css';

export const themeVariables: IncomingThemeVariables = {
  dark: {
    modal: styles.modal,
  },
};

const Home: NextPage = () => {
  const wallet = useWallet();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        

        <div className={styles.walletButtons}>
          <WalletMultiButton />
          <ChatButton wallet={wallet} variables={themeVariables} />
        </div>

        
        
      </main>

      
    </div>
  );
};

export default Home;
